executor: slurm

default-resources:
    mem_mb: 8_000 # default rules memory in MB (you can keep this value)
    gpu: 0

set-resources:
    explorer:
        mem_mb: 512_000
        slurm_partition: scicore # use a valid partition/queue name on your cluster (with enough RAM)
    explorer_raw:
        mem_mb: 512_000
        slurm_partition: scicore
    image_write:
        mem_mb: 64_000
        slurm_partition: scicore # use a valid partition/queue name on your cluster (with a large walltime)
    to_spatialdata:
        mem_mb: 128_000
    patch_segmentation_baysor:
        mem_mb: 128_000
        slurm_partition: scicore # use a valid partition/queue name on your cluster (with at least 2h of walltime)
    patch_segmentation_cellpose:
        mem_mb: 128_000
        qos: gpu6hours
        slurm_partition: rtx4090
        gpu: 1
    patch_segmentation_comseg:
        mem_mb: 128_000
    patch_segmentation_proseg:
        mem_mb: 256_000
        threads: 128
    aggregate:
        mem_mb: 64_000
    patchify_transcripts:
        mem_mb: 32_000
    report:
        mem_mb: 32_000

# other options (you can keep the default values)
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
